/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThreadPanel.java
 *
 * Created on 04.11.2009, 13:40:33
 */

package ro.pub.arh.beam.execution.gui;

import ro.pub.arh.beam.hardware.Opcodes;
import ro.pub.arh.beam.hardware.emulator.core.BeamRegisterFile;
import ro.pub.arh.beam.hardware.emulator.core.ThreadStatus;
import ro.pub.arh.beam.hardware.emulator.tools.Instruction;

/**
 *
 * @author Ares
 */
public class ThreadPanel extends javax.swing.JPanel {

    /** Creates new form ThreadPanel */
    public ThreadPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"R0", "0x00000000"},
                {"R1", "0x00000000"},
                {"R2", "0x00000000"},
                {"R3", "0x00000000"},
                {"R4", "0x00000000"},
                {"R5", "0x00000000"},
                {"R6", "0x00000000"},
                {"R7", "0x00000000"},
                {"R8", "0x00000000"},
                {"R9", "0x00000000"},
                {"R10", "0x00000000"},
                {"R11", "0x00000000"},
                {"R12", "0x00000000"},
                {"R13 (FP)", "0x00000000"},
                {"R14 (SP)", "0x00000000"},
                {"R15 (RET)", "0x00000000"}
            },
            new String [] {
                "RegID", "RegValue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Thread Status", null},
                {"Current instr.", null},
                {"Current opcode", null},
                {"Current bool opcode", null},
                {"Current PC", null}
            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
            .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    public void updateThreadStatus(ThreadStatus _threadStatus){
        jTable2.getModel().setValueAt(_threadStatus.getStatusAsString(), 0, 1);
//        jTable2.getModel().setValueAt(Integer.toHexString(_threadStatus.getStackBase()), 1, 1);
    }

    public void updateRegisterFile(int[] _registerFile){
        for(int i=0; i<BeamRegisterFile.REGISTER_COUNT; i++){
            updateRegisterFile(i, _registerFile[i]);
        }
    }

    public void updateRegisterFile(int _address, int _data){
        jTable1.getModel().setValueAt(Integer.toHexString(_data), _address, 1);
    }

    public void updateInstruction(Instruction _instruction, int _programCounter){
        jTable2.getModel().setValueAt(Integer.toHexString(_instruction.word), 1, 1);
        jTable2.getModel().setValueAt(Opcodes.getNameByOpcode(_instruction.opCode), 2, 1);
        //jTable2.getModel().setValueAt(Opcodes.getNameByBooleanOpcode(_instruction.booleanOpCode), 3, 1);
        jTable2.getModel().setValueAt(Integer.toHexString(_programCounter), 4, 1);
    }
	
}
