// Code auto-generated by method Kernel::genLLVMISelManualCode() from Opincaa lib.


SDValue ct0 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R30 = 1;
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast1, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(8, DL, MVT::i16, true, false);
// R29 = ISHRA(R28, 8);
SDNode *ishra0 = CurDAG->getMachineNode(
                                    Connex::ISHRAV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast1, 0),
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );
unsigned virtReg0 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg0 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(ishra0, 1),
                   DL,
                   virtReg0,
                   // Value copied to register
                   SDValue(ishra0, 0)
                   // Glue
                  );


// CELL_SHL(R28, R30);
SDNode *cellshl0 = CurDAG->getMachineNode(
                                    Connex::CELLSHL_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(vload0, 0),
                                    // glue (or chain) input edge
                                    SDValue(ishra0, 1)
                                    );

SDValue ct2 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(cellshl0, 0)
                                    );

// R23 = SHIFT_REG;
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

// R26 = INDEX;
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(ldsh0, 1)
                                    );

// R25 = R26 & R30;
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload0, 0),
                                    SDValue(ldix0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R24 = R25 == R31;
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and0, 0),
                                    SDValue([NOT_INITIALIZED], 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct3 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct3,
                                    // glue (or chain) input edge
                                    SDValue(eq0, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq0, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

SDValue ct4 = CurDAG->getConstant(8, DL, MVT::i16, true, false);
// R22 = R23 << 8;
SDNode *ishl0 = CurDAG->getMachineNode(
                                    Connex::ISHLV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(ldsh0, 0),
                                    ct4,
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );

SDValue ct5 = CurDAG->getConstant(8, DL, MVT::i16, true, false);
// R29 = R28 >> 8;
SDNode *ishr0 = CurDAG->getMachineNode(
                                    Connex::ISHRV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast1, 0),
                                    ct5,
                                    CurDAG->getRegister(virtReg0, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(ishl0, 1)
                                    );
unsigned virtReg1 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg1 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(ishr0, 1),
                   DL,
                   virtReg1,
                   // Value copied to register
                   SDValue(ishr0, 0)
                   // Glue
                  );


// R29 = R22 | R29;
SDNode *or0 = CurDAG->getMachineNode(
                                    Connex::ORV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(ishr0, 0),
                                    SDValue(ishl0, 0),
                                    CurDAG->getRegister(virtReg1, TYPE_VECTOR_I16)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// END_WHERE;
SDNode *endwhere0 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(or0, 0),
                                    // glue (or chain) input edge
                                    SDValue(or0, 1)
                                    );

SDValue ct6 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop2 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct6,
                                    // glue (or chain) input edge
                                    SDValue(endwhere0, 1)
                                    );

