// Code auto-generated by method Kernel::genLLVMISelManualCode()
//   from the OPINCAA lib, from kernel Add.i64.
// You can put this code in the Select() method of the [Target]SelectionDAGISel
//   class of your back end (or MAYBE in the
//   ISelLowering pass).
// Number of instructions generated: 40.




SDValue ct0 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R30 = 0;// Instr #0
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast2, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R31 = 1;// Instr #1
SDNode *vload1 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );

SDValue ct2 = CurDAG->getConstant(3, DL, MVT::i16, true, false);
// R29 = 3;// Instr #2
SDNode *vload2 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(vload1, 1)
                                    );

// R25 = R24 + R23;// Instr #3
SDNode *add0 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(nodeOpSrcCast2, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload2, 1)
                                    );

// R26 = ADDC(R30, R30);// Instr #4
SDNode *addc0 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(add0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R20 = INDEX;// Instr #5
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(addc0, 1)
                                    );

// R20 = R20 & R29;// Instr #6
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload2, 0),
                                    SDValue(ldix0, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldix0, 1)
                                    );

// R20 = R20 == R29;// Instr #7
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and0, 0),
                                    SDValue(vload2, 0),
                                    // glue (or chain) input edge
                                    SDValue(and0, 1)
                                    );

SDValue ct3 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #8
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct3,
                                    // glue (or chain) input edge
                                    SDValue(eq0, 1)
                                    );

// WHERE_EQ;// Instr #9
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq0, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

SDValue ct4 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R26 = 0;// Instr #10
SDNode *vload3 = CurDAG->getMachineNode(
                                    Connex::VLOAD_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct4,
                                    SDValue(addc0, 0),
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );

// END_WHERE;// Instr #11
SDNode *endwhere0 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(vload3, 1)
                                    );

// CELL_SHR(R26, R31);// Instr #12
SDNode *cellshr0 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(vload3, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere0, 0)
                                    );

SDValue ct5 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #13
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct5,
                                    // glue (or chain) input edge
                                    SDValue(cellshr0, 0)
                                    );

// R26 = SHIFT_REG;// Instr #14
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

// R25 = R26 + R25;// Instr #15
SDNode *add1 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(add0, 0),
                                    SDValue(ldsh0, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldsh0, 1)
                                    );

// R26 = ADDC(R30, R30);// Instr #16
SDNode *addc1 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(add1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R20 = INDEX;// Instr #17
SDNode *ldix1 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(addc1, 1)
                                    );

// R20 = R20 & R29;// Instr #18
SDNode *and1 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload2, 0),
                                    SDValue(ldix1, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldix1, 1)
                                    );

// R20 = R20 == R29;// Instr #19
SDNode *eq1 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and1, 0),
                                    SDValue(vload2, 0),
                                    // glue (or chain) input edge
                                    SDValue(and1, 1)
                                    );

SDValue ct6 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #20
SDNode *nop2 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct6,
                                    // glue (or chain) input edge
                                    SDValue(eq1, 1)
                                    );

// WHERE_EQ;// Instr #21
SDNode *whereeq1 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq1, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop2, 0)
                                    );

SDValue ct7 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R26 = 0;// Instr #22
SDNode *vload4 = CurDAG->getMachineNode(
                                    Connex::VLOAD_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct7,
                                    SDValue(addc1, 0),
                                    // glue (or chain) input edge
                                    SDValue(whereeq1, 1)
                                    );

// END_WHERE;// Instr #23
SDNode *endwhere1 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(vload4, 1)
                                    );

// CELL_SHR(R26, R31);// Instr #24
SDNode *cellshr1 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(vload4, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere1, 0)
                                    );

SDValue ct8 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #25
SDNode *nop3 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct8,
                                    // glue (or chain) input edge
                                    SDValue(cellshr1, 0)
                                    );

// R26 = SHIFT_REG;// Instr #26
SDNode *ldsh1 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(nop3, 0)
                                    );

// R25 = R26 + R25;// Instr #27
SDNode *add2 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(add1, 0),
                                    SDValue(ldsh1, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldsh1, 1)
                                    );

// R26 = ADDC(R30, R30);// Instr #28
SDNode *addc2 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(add2, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R20 = INDEX;// Instr #29
SDNode *ldix2 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(addc2, 1)
                                    );

// R20 = R20 & R29;// Instr #30
SDNode *and2 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload2, 0),
                                    SDValue(ldix2, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldix2, 1)
                                    );

// R20 = R20 == R29;// Instr #31
SDNode *eq2 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and2, 0),
                                    SDValue(vload2, 0),
                                    // glue (or chain) input edge
                                    SDValue(and2, 1)
                                    );

SDValue ct9 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #32
SDNode *nop4 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct9,
                                    // glue (or chain) input edge
                                    SDValue(eq2, 1)
                                    );

// WHERE_EQ;// Instr #33
SDNode *whereeq2 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq2, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop4, 0)
                                    );

SDValue ct10 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R26 = 0;// Instr #34
SDNode *vload5 = CurDAG->getMachineNode(
                                    Connex::VLOAD_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct10,
                                    SDValue(addc2, 0),
                                    // glue (or chain) input edge
                                    SDValue(whereeq2, 1)
                                    );

// END_WHERE;// Instr #35
SDNode *endwhere2 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(vload5, 1)
                                    );

// CELL_SHR(R26, R31);// Instr #36
SDNode *cellshr2 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(vload5, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere2, 0)
                                    );

SDValue ct11 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;// Instr #37
SDNode *nop5 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct11,
                                    // glue (or chain) input edge
                                    SDValue(cellshr2, 0)
                                    );

// R26 = SHIFT_REG;// Instr #38
SDNode *ldsh2 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    // glue (or chain) input edge
                                    SDValue(nop5, 0)
                                    );

// R25 = R26 + R25;// Instr #39
SDNode *add3 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(add2, 0),
                                    SDValue(ldsh2, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldsh2, 1)
                                    );

