// Copied from /home/asusu/LLVM/llvm38Nov2016/llvm/build40/bin/Tests/NEW_v128i16/opincaa_standalone_app/25k_int32/MUL_i32_manual/Complemented_radix_216_representation/DumpISel_OpincaaCodeGen.cpp

// R27 is REG_SRC1. It is represented by result of nodeOpSrcCast1.
// R28 is REG_SRC2. It is represented by result of nodeOpSrcCast2.


// Code auto-generated by method Kernel::genLLVMISelManualCode() from Opincaa lib.



SDValue ct0 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R31 = 0;
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast2, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R30 = 1;
SDNode *vload1 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );

// R28 * R27;
SDNode *mult0 = CurDAG->getMachineNode(
                                    Connex::MULT_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast2, 0),
                                    SDValue(nodeOpSrcCast1, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload1, 1)
                                    );

// R26 = MULT_LOW();
SDNode *multlo0 = CurDAG->getMachineNode(
                                    Connex::MULTLO_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(mult0, 0)
                                    );
unsigned virtReg0 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg0 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(multlo0, 1),
                   DL,
                   virtReg0,
                   // Value copied to register
                   SDValue(multlo0, 0)
                   // Glue
                  );


// R25 = MULT_HIGH();
SDNode *multhi0 = CurDAG->getMachineNode(
                                    Connex::MULTHI_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(multlo0, 1)
                                    );

// CELL_SHR(R27, R30);
SDNode *cellshr0 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(multhi0, 1)
                                    );

SDValue ct2 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(cellshr0, 0)
                                    );

// R24 = SHIFT_REG;
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

// R24 * R28;
SDNode *mult1 = CurDAG->getMachineNode(
                                    Connex::MULT_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(ldsh0, 0),
                                    SDValue(nodeOpSrcCast2, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R0 = MULT_LOW();
SDNode *multlo1 = CurDAG->getMachineNode(
                                    Connex::MULTLO_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(mult1, 0)
                                    );

// CELL_SHR(R28, R30);
SDNode *cellshr1 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast2, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(multlo1, 1)
                                    );

SDValue ct3 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct3,
                                    // glue (or chain) input edge
                                    SDValue(cellshr1, 0)
                                    );

// R23 = SHIFT_REG;
SDNode *ldsh1 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

// R23 * R27;
SDNode *mult2 = CurDAG->getMachineNode(
                                    Connex::MULT_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(ldsh1, 0),
                                    SDValue(nodeOpSrcCast1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R1 = MULT_LOW();
SDNode *multlo2 = CurDAG->getMachineNode(
                                    Connex::MULTLO_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(mult2, 0)
                                    );

// CELL_SHR(R25, R30);
SDNode *cellshr2 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(multhi0, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(multlo2, 1)
                                    );

SDValue ct4 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop2 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct4,
                                    // glue (or chain) input edge
                                    SDValue(cellshr2, 0)
                                    );

// R21 = SHIFT_REG;
SDNode *ldsh2 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(nop2, 0)
                                    );

// R14 = INDEX;
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(ldsh2, 1)
                                    );

// R13 = R14 & R30;
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload1, 0),
                                    SDValue(ldix0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R12 = R13 == R30;
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(and0, 0),
                                    SDValue(vload1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct5 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop3 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct5,
                                    // glue (or chain) input edge
                                    SDValue(eq0, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(eq0, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop3, 0)
                                    );

// R26 = R21 | R21;
SDNode *or0 = CurDAG->getMachineNode(
                                    Connex::ORV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(ldsh2, 0),
                                    SDValue(ldsh2, 0),
                                    CurDAG->getRegister(virtReg0, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );
unsigned virtReg1 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg1 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(or0, 1),
                   DL,
                   virtReg1,
                   // Value copied to register
                   SDValue(or0, 0)
                   // Glue
                  );


// R26 = R0 + R26;
SDNode *add0 = CurDAG->getMachineNode(
                                    Connex::ADDV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(or0, 0),
                                    SDValue(multlo1, 0),
                                    CurDAG->getRegister(virtReg1, TYPE_VECTOR_I16)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );
unsigned virtReg2 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg2 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(add0, 1),
                   DL,
                   virtReg2,
                   // Value copied to register
                   SDValue(add0, 0)
                   // Glue
                  );


// R26 = R1 + R26;
SDNode *add1 = CurDAG->getMachineNode(
                                    Connex::ADDV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(add0, 0),
                                    SDValue(multlo2, 0),
                                    CurDAG->getRegister(virtReg2, TYPE_VECTOR_I16)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// END_WHERE;
SDNode *resH /*endwhere0*/ = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(add1, 0),
                                    // glue (or chain) input edge
                                    SDValue(add1, 1)
                                    );

