// Code auto-generated by method Kernel::genLLVMISelManualCode() from Opincaa lib.



SDValue ct0 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R31 = 0;
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast2, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R30 = 1;
SDNode *vload1 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );

// R29 = R27 + R28;
SDNode *add0 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast2, 0),
                                    SDValue(nodeOpSrcCast1, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload1, 1)
                                    );

// R23 = ADDC(R31, R31);
SDNode *addc0 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(add0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );
unsigned virtReg0 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg0 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(addc0, 1),
                   DL,
                   virtReg0,
                   // Value copied to register
                   SDValue(addc0, 0)
                   // Glue
                  );


SDValue ct2 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R20 = 0;
SDNode *vload2 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(addc0, 1)
                                    );
unsigned virtReg1 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg1 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(vload2, 1),
                   DL,
                   virtReg1,
                   // Value copied to register
                   SDValue(vload2, 0)
                   // Glue
                  );


// R26 = INDEX;
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(vload2, 1)
                                    );

// R25 = R26 & R30;
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload1, 0),
                                    SDValue(ldix0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R24 = R25 == R30;
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and0, 0),
                                    SDValue(vload1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct3 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct3,
                                    // glue (or chain) input edge
                                    SDValue(eq0, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq0, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

SDValue ct4 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R20 = R23 << 0;
SDNode *ishl0 = CurDAG->getMachineNode(
                                    Connex::ISHLV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(addc0, 0),
                                    ct4,
                                    CurDAG->getRegister(virtReg1, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );

SDValue ct5 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R23 = 0;
SDNode *vload3 = CurDAG->getMachineNode(
                                    Connex::VLOAD_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct5,
                                    CurDAG->getRegister(virtReg0, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(ishl0, 1)
                                    );

// END_WHERE;
SDNode *endwhere0 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload3, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload3, 1)
                                    );

// CELL_SHR(R23, R30);
SDNode *cellshr0 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(endwhere0, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere0, 1)
                                    );

SDValue ct6 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct6,
                                    // glue (or chain) input edge
                                    SDValue(cellshr0, 0)
                                    );

// R21 = SHIFT_REG;
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

// R22 = R21 + R29;
SDNode *add1 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(add0, 0),
                                    SDValue(ldsh0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R0 = ADDC(R31, R31);
SDNode *addc1 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(add1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R1 = R20 | R0;
SDNode *or0 = CurDAG->getMachineNode(
                                    Connex::ORV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(addc1, 0),
                                    SDValue(ishl0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct7 = CurDAG->getConstant(-1, DL, MVT::i16, true, false);
// R19 = -1;
SDNode *vload4 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct7,
                                    // glue (or chain) input edge
                                    SDValue(or0, 1)
                                    );

// R2 = R1 + R19;
SDNode *add2 = CurDAG->getMachineNode(
                                    Connex::ADDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload4, 0),
                                    SDValue(or0, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload4, 1)
                                    );

