#------------------------------------------------------------------------------#
# Linux Makefile for OPINCAA API.                                              #
#------------------------------------------------------------------------------#

ARCH = connex16-hm-generic
DEPTH = ../../
# Don't forget about the last '/'

include $(DEPTH)Makefile.base
