#------------------------------------------------------------------------------#
# Linux Makefile for OPINCAA API.                                              #
#------------------------------------------------------------------------------#

ARCH = connex-rc
DEPTH = ../../
# Don't forget about the last '/'

include $(DEPTH)makefile.base
