/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ro_pub_arh_beam_simulator_ConnexBEAMSimulator */

#ifndef _Included_ro_pub_arh_beam_simulator_ConnexBEAMSimulator
#define _Included_ro_pub_arh_beam_simulator_ConnexBEAMSimulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    initializeSimulator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_initializeSimulator
  (JNIEnv *, jobject);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    finalizeSimulator
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_finalizeSimulator
  (JNIEnv *, jobject);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    writeFlash
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_writeFlash
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    readFlash
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_readFlash
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    writeDDR
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_writeDDR
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    readDDR
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_readDDR
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    run
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_run
  (JNIEnv *, jobject, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    resetAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_resetAll
  (JNIEnv *, jobject, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    setBreakpoint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_setBreakpoint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    readRegisters
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_readRegisters
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    readPC
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_readPC
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    getCycles
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_getCycles
  (JNIEnv *, jobject);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    readSerial
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_readSerial
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ro_pub_arh_beam_simulator_ConnexBEAMSimulator
 * Method:    writeSerial
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_ro_pub_arh_beam_simulator_ConnexBEAMSimulator_writeSerial
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
