// Code auto-generated by method Kernel::genLLVMISelManualCode() from Opincaa lib.



SDValue ct0 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R31 = 0;
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast2, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R30 = 1;
SDNode *vload1 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );

// R29 = R27 - R28;
SDNode *sub0 = CurDAG->getMachineNode(
                                    Connex::SUBV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(nodeOpSrcCast2, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload1, 1)
                                    );

// R23 = ADDC(R31, R31);
SDNode *addc0 = CurDAG->getMachineNode(
                                    Connex::ADDCV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload0, 0),
                                    SDValue(vload0, 0),
                                    SDValue(sub0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );
unsigned virtReg0 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg0 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(addc0, 1),
                   DL,
                   virtReg0,
                   // Value copied to register
                   SDValue(addc0, 0)
                   // Glue
                  );


// R26 = INDEX;
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(addc0, 1)
                                    );

// R25 = R26 & R30;
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload1, 0),
                                    SDValue(ldix0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R24 = R25 == R30;
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(and0, 0),
                                    SDValue(vload1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct2 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(eq0, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(eq0, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

SDValue ct3 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R23 = 0;
SDNode *vload2 = CurDAG->getMachineNode(
                                    Connex::VLOAD_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    ct3,
                                    CurDAG->getRegister(virtReg0, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );

// END_WHERE;
SDNode *endwhere0 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(vload2, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload2, 1)
                                    );

// CELL_SHR(R23, R30);
SDNode *cellshr0 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Glue,
                                    SDValue(endwhere0, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere0, 1)
                                    );

SDValue ct4 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Glue,
                                    ct4,
                                    // glue (or chain) input edge
                                    SDValue(cellshr0, 0)
                                    );

// R0 = SHIFT_REG;
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

// R1 = R29 - R0;
SDNode *sub1 = CurDAG->getMachineNode(
                                    Connex::SUBV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Glue,
                                    SDValue(sub0, 0),
                                    SDValue(ldsh0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

