// Code auto-generated by method Kernel::genLLVMISelManualCode() from Opincaa lib.



SDValue ct0 = CurDAG->getConstant(0, DL, MVT::i16, true, false);
// R31 = 0;
SDNode *vload0 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct0,
                                    // glue (or chain) input edge
                                    SDValue(nodeOpSrcCast1, 1)
                                    );

SDValue ct1 = CurDAG->getConstant(1, DL, MVT::i16, true, false);
// R30 = 1;
SDNode *vload1 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct1,
                                    // glue (or chain) input edge
                                    SDValue(vload0, 1)
                                    );

SDValue ct2 = CurDAG->getConstant(16, DL, MVT::i16, true, false);
// R10 = 16;
SDNode *vload2 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct2,
                                    // glue (or chain) input edge
                                    SDValue(vload1, 1)
                                    );

SDValue ct3 = CurDAG->getConstant(31, DL, MVT::i16, true, false);
// R8 = 31;
SDNode *vload3 = CurDAG->getMachineNode(
                                    Connex::VLOAD_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    ct3,
                                    // glue (or chain) input edge
                                    SDValue(vload2, 1)
                                    );

// R0 = R27 & R8;
SDNode *and0 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(vload3, 0),
                                    SDValue(nodeOpSrcCast2, 0),
                                    // glue (or chain) input edge
                                    SDValue(vload3, 1)
                                    );

// R9 = INDEX;
SDNode *ldix0 = CurDAG->getMachineNode(
                                    Connex::LDIX_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(and0, 1)
                                    );

// R25 = R9 & R30;
SDNode *and1 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(vload1, 0),
                                    SDValue(ldix0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R1 = R9 & R30;
SDNode *and2 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload1, 0),
                                    SDValue(ldix0, 0),
                                    // glue (or chain) input edge
                                    SDValue(and1, 1)
                                    );

// CELL_SHR(R0, R1);
SDNode *cellshr0 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(and0, 0),
                                    SDValue(and2, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct4 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop0 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct4,
                                    // glue (or chain) input edge
                                    SDValue(cellshr0, 0)
                                    );

// R2 = SHIFT_REG;
SDNode *ldsh0 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    // glue (or chain) input edge
                                    SDValue(nop0, 0)
                                    );

// R20 = R10 < R2;
SDNode *lt0 = CurDAG->getMachineNode(
                                    Connex::LT_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(vload2, 0),
                                    SDValue(ldsh0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R29 = R28 << R2;
SDNode *shl0 = CurDAG->getMachineNode(
                                    Connex::SHLV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(ldsh0, 0),
                                    // glue (or chain) input edge
                                    SDValue(lt0, 1)
                                    );
unsigned virtReg0 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg0 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(shl0, 1),
                   DL,
                   virtReg0,
                   // Value copied to register
                   SDValue(shl0, 0)
                   // Glue
                  );


// CELL_SHR(R28, R30);
SDNode *cellshr1 = CurDAG->getMachineNode(
                                    Connex::CELLSHR_H,
                                    DL,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(shl0, 1)
                                    );

SDValue ct5 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop1 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct5,
                                    // glue (or chain) input edge
                                    SDValue(cellshr1, 0)
                                    );

// R23 = SHIFT_REG;
SDNode *ldsh1 = CurDAG->getMachineNode(
                                    Connex::LDSH_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    // glue (or chain) input edge
                                    SDValue(nop1, 0)
                                    );

// R3 = R25 == R30;
SDNode *eq0 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(and1, 0),
                                    SDValue(vload1, 0),
                                    // glue (or chain) input edge
                                    SDValue(ldsh1, 1)
                                    );

// R24 = R20 & R3;
SDNode *and3 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(eq0, 0),
                                    SDValue(lt0, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R19 = R24 == R30;
SDNode *eq1 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(and3, 0),
                                    SDValue(vload1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct6 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop2 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct6,
                                    // glue (or chain) input edge
                                    SDValue(eq1, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq0 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(eq1, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop2, 0)
                                    );

// R21 = R2 - R10;
SDNode *sub0 = CurDAG->getMachineNode(
                                    Connex::SUBV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(ldsh0, 0),
                                    SDValue(vload2, 0),
                                    // glue (or chain) input edge
                                    SDValue(whereeq0, 1)
                                    );
unsigned virtReg1 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg1 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(sub0, 1),
                   DL,
                   virtReg1,
                   // Value copied to register
                   SDValue(sub0, 0)
                   // Glue
                  );


// R29 = R23 << R21;
SDNode *shl1 = CurDAG->getMachineNode(
                                    Connex::SHLV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(ldsh1, 0),
                                    SDValue(sub0, 0),
                                    CurDAG->getRegister(virtReg0, TYPE_VECTOR_I16)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );
unsigned virtReg2 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg2 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(shl1, 1),
                   DL,
                   virtReg2,
                   // Value copied to register
                   SDValue(shl1, 0)
                   // Glue
                  );


// END_WHERE;
SDNode *endwhere0 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(shl1, 0),
                                    // glue (or chain) input edge
                                    SDValue(shl1, 1)
                                    );

// R4 = R30 - R20;
SDNode *sub1 = CurDAG->getMachineNode(
                                    Connex::SUBV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload1, 0),
                                    SDValue(lt0, 0),
                                    // glue (or chain) input edge
                                    SDValue(endwhere0, 1)
                                    );

// R5 = R4 & R25;
SDNode *and4 = CurDAG->getMachineNode(
                                    Connex::ANDV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(and1, 0),
                                    SDValue(sub1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R6 = R5 == R30;
SDNode *eq2 = CurDAG->getMachineNode(
                                    Connex::EQ_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(and4, 0),
                                    SDValue(vload1, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

SDValue ct7 = CurDAG->getConstant(1 /* Num of cycles to NOP */, DL, MVT::i16, true, false);
// NOP;
SDNode *nop3 = CurDAG->getMachineNode(
                                    Connex::NOP_BPF,
                                    DL,
                                    MVT::Other,
                                    ct7,
                                    // glue (or chain) input edge
                                    SDValue(eq2, 1)
                                    );

// WHERE_EQ;
SDNode *whereeq1 = CurDAG->getMachineNode(
                                    Connex::WHEREEQ,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(eq2, 0),
                                    // glue (or chain) input edge
                                    SDValue(nop3, 0)
                                    );

// R21 = R10 - R27;
SDNode *sub2 = CurDAG->getMachineNode(
                                    Connex::SUBV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    SDValue(vload2, 0),
                                    SDValue(nodeOpSrcCast2, 0),
                                    CurDAG->getRegister(virtReg1, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(whereeq1, 1)
                                    );

// R22 = R23 >> R21;
SDNode *shr0 = CurDAG->getMachineNode(
                                    Connex::SHRV_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(ldsh1, 0),
                                    SDValue(sub2, 0)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// R29 = R28 << R27;
SDNode *shl2 = CurDAG->getMachineNode(
                                    Connex::SHLV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(nodeOpSrcCast1, 0),
                                    SDValue(nodeOpSrcCast2, 0),
                                    CurDAG->getRegister(virtReg2, TYPE_VECTOR_I16),
                                    // glue (or chain) input edge
                                    SDValue(shr0, 1)
                                    );
unsigned virtReg3 = RegInfo->createVirtualRegister(&Connex::MSA128HRegClass);
SDValue copyToReg3 = CurDAG->getCopyToReg(
                   // glue (or chain) input edge
                   SDValue(shl2, 1),
                   DL,
                   virtReg3,
                   // Value copied to register
                   SDValue(shl2, 0)
                   // Glue
                  );


// R29 = R29 | R22;
SDNode *or0 = CurDAG->getMachineNode(
                                    Connex::ORV_SPECIAL_H,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(shr0, 0),
                                    SDValue(shl2, 0),
                                    CurDAG->getRegister(virtReg3, TYPE_VECTOR_I16)
                                    // no need for glue or chain input (since it normally consumes the output of the predecessor)
                                    );

// END_WHERE;
SDNode *endwhere1 = CurDAG->getMachineNode(
                                    Connex::END_WHERE,
                                    DL,
                                    TYPE_VECTOR_I16,
                                    MVT::Other,
                                    SDValue(or0, 0),
                                    // glue (or chain) input edge
                                    SDValue(or0, 1)
                                    );

